In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [ ]:
po = pd.read_json

In [3]:
disney = pd.read_csv(r'C:\Users\DIEZ\Desktop\MySpace\Practicas\PI01_DATA05-main\Datasets\disney_plus_titles.csv')

In [4]:
disney.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       1450 non-null   object
 1   type          1450 non-null   object
 2   title         1450 non-null   object
 3   director      977 non-null    object
 4   cast          1260 non-null   object
 5   country       1231 non-null   object
 6   date_added    1447 non-null   object
 7   release_year  1450 non-null   int64
 8   rating        1447 non-null   object
 9   duration      1450 non-null   object
 10  listed_in     1450 non-null   object
 11  description   1450 non-null   object
dtypes: int64(1), object(11)
memory usage: 136.1+ KB

In [5]:
disney.isna().sum()

show_id           0
type              0
title             0
director        473
cast            190
country         219
date_added        3
release_year      0
rating            3
duration          0
listed_in         0
description       0
dtype: int64

In [6]:
disney['director'].fillna('Sin Dato', inplace = True)
disney['cast'].fillna('Sin Dato', inplace = True)
disney['country'].fillna('Sin Dato', inplace = True)
disney['rating'].fillna('Sin Dato', inplace = True)
disney['plataforma'] = 'disney'

In [7]:
#disney['date_added'] = disney['date_added'].str.lstrip()
#disney['date_added'] = disney['date_added'].str.rstrip()
disney['date_added'] = pd.to_datetime(disney['date_added'], format = '%B %d, %Y')

In [8]:
disney.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       1450 non-null   object
 1   type          1450 non-null   object
 2   title         1450 non-null   object
 3   director      1450 non-null   object
 4   cast          1450 non-null   object
 5   country       1450 non-null   object
 6   date_added    1447 non-null   datetime64[ns]
 7   release_year  1450 non-null   int64
 8   rating        1450 non-null   object
 9   duration      1450 non-null   object
 10  listed_in     1450 non-null   object
 11  description   1450 non-null   object
 12  plataforma    1450 non-null   object
dtypes: datetime64[ns](1), int64(1), object(11)
memory usage: 147.4+ KB

In [9]:
hulu = pd.read_csv(r'C:\Users\DIEZ\Desktop\MySpace\Practicas\PI01_DATA05-main\Datasets\hulu_titles.csv')

In [10]:
hulu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3073 entries, 0 to 3072
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       3073 non-null   object
 1   type          3073 non-null   object
 2   title         3073 non-null   object
 3   director      3 non-null      object
 4   cast          0 non-null      float64
 5   country       1620 non-null   object
 6   date_added    3045 non-null   object
 7   release_year  3073 non-null   int64
 8   rating        2553 non-null   object
 9   duration      2594 non-null   object
 10  listed_in     3073 non-null   object
 11  description   3069 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 288.2+ KB

In [11]:
hulu['director'].fillna('Sin Dato', inplace = True)
hulu['cast'].astype(str)
hulu['country'].fillna('Sin Dato', inplace = True)
hulu['rating'].fillna('Sin Dato', inplace = True)
hulu['cast'].fillna('Sin Dato', inplace = True)
hulu['show_id'].fillna('Sin Dato', inplace = True)
hulu['type'].fillna('Sin Dato', inplace = True)
hulu['title'].fillna('Sin Dato', inplace = True)
hulu['release_year'].fillna(0, inplace = True)
hulu['duration'].fillna('Sin Dato', inplace = True)
hulu['description'].fillna('Sin Dato', inplace = True)
hulu['release_year'].astype(int)
hulu['plataforma'] = 'hulu'
hulu['date_added'] = pd.to_datetime(hulu['date_added'], format = '%B %d, %Y')

In [12]:
amazon = pd.read_csv(r'C:\Users\DIEZ\Desktop\MySpace\Practicas\PI01_DATA05-main\Datasets\amazon_prime_titles.csv')

In [13]:
amazon['director'].fillna('Sin Dato', inplace = True)
amazon['country'].fillna('Sin Dato', inplace = True)
amazon['rating'].fillna('Sin Dato', inplace = True)
amazon['cast'].fillna('Sin Dato', inplace = True)
amazon['show_id'].fillna('Sin Dato', inplace = True)
amazon['type'].fillna('Sin Dato', inplace = True)
amazon['title'].fillna('Sin Dato', inplace = True)
amazon['release_year'].fillna(0, inplace = True)
amazon['duration'].fillna('Sin Dato', inplace = True)
amazon['description'].fillna('Sin Dato', inplace = True)
amazon['release_year'].astype(int)
amazon['date_added'] = pd.to_datetime(amazon['date_added'], format = '%B %d, %Y')
amazon['plataforma'] = 'amazon'

In [14]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   object
 1   type          9668 non-null   object
 2   title         9668 non-null   object
 3   director      9668 non-null   object
 4   cast          9668 non-null   object
 5   country       9668 non-null   object
 6   date_added    155 non-null    datetime64[ns]
 7   release_year  9668 non-null   int64
 8   rating        9668 non-null   object
 9   duration      9668 non-null   object
 10  listed_in     9668 non-null   object
 11  description   9668 non-null   object
 12  plataforma    9668 non-null   object
dtypes: datetime64[ns](1), int64(1), object(11)
memory usage: 982.0+ KB

In [15]:
netflix = pd.read_json(r'C:\Users\DIEZ\Desktop\MySpace\Practicas\PI01_DATA05-main\Datasets\netflix_titles.json')

In [16]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 894.5+ KB

In [17]:
netflix['director'].fillna('Sin Dato', inplace = True)
netflix['country'].fillna('Sin Dato', inplace = True)
netflix['rating'].fillna('Sin Dato', inplace = True)
netflix['cast'].fillna('Sin Dato', inplace = True)
netflix['show_id'].fillna('Sin Dato', inplace = True)
netflix['type'].fillna('Sin Dato', inplace = True)
netflix['title'].fillna('Sin Dato', inplace = True)
netflix['release_year'].fillna(0, inplace = True)
netflix['duration'].fillna('Sin Dato', inplace = True)
netflix['description'].fillna('Sin Dato', inplace = True)
netflix['release_year'].astype(int)
netflix['plataforma'] = 'netflix'
netflix['date_added'] = netflix['date_added'].str.lstrip()
netflix['date_added'] = netflix['date_added'].str.rstrip()
netflix['date_added'] = pd.to_datetime(netflix['date_added'], format = '%B %d, %Y')

In [49]:
data = pd.read_csv('https://raw.githubusercontent.com/Luismadrid77/Data_engineering/main/peliculas.csv')

In [50]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma,duration_int,duration_str
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",Sin Dato,2021-11-26,2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!,disney,23,min
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",Sin Dato,2021-11-26,1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...,disney,91,min
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,2021-11-26,2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.,disney,23,min
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",Sin Dato,2021-11-26,2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!",disney,41,min
4,s5,TV Show,The Beatles: Get Back,Sin Dato,"John Lennon, Paul McCartney, George Harrison, ...",Sin Dato,2021-11-25,2021,Sin Dato,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...,disney,1,Season

In [18]:
amazon.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,2021-03-30,2014,Sin Dato,113 min,"Comedy, Drama",A small fishing village must procure a local d...,amazon
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,2021-03-30,2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,amazon
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,2021-03-30,2017,Sin Dato,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,amazon
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,2021-03-30,2014,Sin Dato,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",amazon
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,2021-03-30,1989,Sin Dato,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,amazon

In [19]:
"""
    Separamos la cantidad de minutos con la palabra min
"""
separacion_hulu = hulu['duration'].str.split(' ', n = 1, expand = True)
separacion_disney = disney['duration'].str.split(' ', n = 1, expand = True)
separacion_amazon = amazon['duration'].str.split(' ', n = 1, expand = True)
separacion_netflix = netflix['duration'].str.split(' ', n = 1, expand = True)

hulu['duration'] = separacion_hulu[0]
hulu['duration'] = separacion_hulu[1]

amazon['duration'] = separacion_amazon[0]
amazon['duration'] = separacion_hulu[1]

disney['duration'] = separacion_disney[0]
disney['duration'] = separacion_disney[1]

netflix['duration'] = separacion_netflix[0]
netflix['duration'] = separacion_netflix[1]

In [20]:
amazon.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,2021-03-30,2014,Sin Dato,Dato,"Comedy, Drama",A small fishing village must procure a local d...,amazon
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,2021-03-30,2018,13+,min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,amazon
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,2021-03-30,2017,Sin Dato,min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,amazon
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,2021-03-30,2014,Sin Dato,min,Documentary,"Pink breaks the mold once again, bringing her ...",amazon
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,2021-03-30,1989,Sin Dato,min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,amazon

In [21]:
cadena_conexion = 'mysql+pymysql://root:123456789@localhost:3306/proyecto01'
conexion = create_engine(cadena_conexion)

In [22]:
conexion_ip = create_engine(cadena_conexion)

In [23]:
def importar_tablas(archivo, nombre_archivo):
    
    archivo.to_sql(name = nombre_archivo , con = conexion_ip , index = False)

In [24]:
importar_tablas(disney, 'disney')
importar_tablas(hulu, 'hulu')
importar_tablas(amazon, 'amazon')
importar_tablas(netflix, 'netflix')

RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

In [ ]:
def importar_Mysql(df1,df2,df3,df4, nombre_archivo):
    archivo = pd.concat([df1,df2,df3,df4])
    archivo.to_csv('peliculas')
    archivo.to_sql(name = nombre_archivo , con = conexion_ip , index = False)

In [29]:
importar_Mysql(disney,hulu,amazon,netflix,'peliculas')

NameError: name 'importar_Mysql' is not defined

In [26]:
peliculas = pd.concat([disney,hulu,amazon,netflix])

In [32]:
carga = r'C:\Users\DIEZ\Desktop\MySpace\Practicas\PI01_DATA05-main\peliculas.csv'
peliculas.to_csv(carga,index = False)